language: python

python: 2.7

env:
- TOXENV=py27
- TOXENV=py34
- TOXENV=py36
- TOXENV=py37
- TOXENV=py38
- TOXENV=py39
- TOXENV=py310
- TOXENV=py311
- TOXENV=py312
- TOXENV=cov

branches:
  only:
    - master
    - develop

install: pip install --quiet --use-mirrors tox

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
  fi
